### ISSUE TITLE
Support for Datastax java-driver v4+?

### ISSUE THREAD

**Issue by natalie-zamani** [dropwizard/dropwizard-cassandra#3]
The java-driver in version 4 is not byte-code compatible with previous versions, and the client has changed pretty significantly, so supporting both 3 and 4 simultaneously (in separate modules) may be a good idea, while most of the world probably isn't on v4.

**Comment by minkenlai** [comment]
+1 @natalie-zamani Are you working on this?

**Comment by natalie-zamani** [comment]
@minkenlai I’m not actively working on this currently, but I’m happy to review contributions that address this!

If there’s enough interest, and no other contributions, it is something I can prioritize working on.
