### ISSUE TITLE
Support for max_schema_agreement_wait setting

### ISSUE THREAD

**Issue by jdonenine** [dropwizard/dropwizard-cassandra#83]
The comprehensive list of settings

https://github.com/dropwizard/dropwizard-cassandra#comprehensive

Does not currently include any properties that appear to be for setting the `max_schema_agreement_wait`.

We need to add this setting here so that it can be leveraged in Reaper:  https://github.com/thelastpickle/cassandra-reaper/issues/1134

**Comment by joschi** [comment]
@pdehlke @jdonenine Would one of you be willing and able to provide a pull request for adding this configuration setting?

You'd need to add it to `CassandraFactory` and make sure it's being applied when building the driver:

https://github.com/dropwizard/dropwizard-cassandra/blob/4b96c480eb09db65a2134967ae1f9a738cda86d5/src/main/java/io/dropwizard/cassandra/CassandraFactory.java#L280-L309

**Comment by jdonenine** [comment]
Months late here @joschi, but you can assign the issue to me, I'll get a PR up for the change sometime this week.

**Comment by joschi** [comment]
@jdonenine Thanks for your contribution!

The new settings have been released as part of https://github.com/dropwizard/dropwizard-cassandra/releases/tag/dropwizard-cassandra-2.1.1 and https://github.com/dropwizard/dropwizard-cassandra/releases/tag/dropwizard-cassandra-2.0.4.
